---
- name: Download and unzip file
  ansible.builtin.unarchive:
    src: "{{ github_project }}/releases/download/v{{ swag_version }}/swag_{{ swag_version }}_Linux_x86_64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  changed_when: False

- name: Copy files to runtime directory
  ansible.builtin.copy:
    src: "/tmp/swag"
    dest: "/usr/local/bin"
    mode: 0755
    remote_src: yes