---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Set download directory for all users to use
      ansible.builtin.set_fact:
        swag_runtime_dir: "/usr/local/bin"

    - name: Find the swag file
      ansible.builtin.stat:
        path: "{{ swag_runtime_dir }}/swag"
      register: swag_file

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ swag_file.stat }}"

    - name: Assert that swag exists
      ansible.builtin.assert:
        that: swag_file.stat.exists

    - name: Assert that swag is executable
      ansible.builtin.assert:
        that: swag_file.stat.executable
